# Generated by Django 5.1.4 on 2025-03-10 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emploees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooles', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('holding_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoldingMainMenu.holding')),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('square', models.IntegerField()),
                ('wardrobe', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('status', models.IntegerField(default=0, editable=False)),
                ('holding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldingMainMenu.holding')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=255)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldingMainMenu.venues')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='holdings/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldingMainMenu.venues')),
            ],
        ),
    ]
