# Generated by Django 5.1.4 on 2024-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('square', models.FloatField()),
                ('wardrobe', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
