# Generated by Django 5.2 on 2025-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldingMainMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
