# Generated by Django 5.1.4 on 2025-02-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldingMainMenu', '0002_alter_venues_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
