# Generated by Django 5.1.4 on 2025-02-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldingMainMenu', '0004_emploees_user_id_emploees_holding_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/holdings/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoldingMainMenu.venues')),
            ],
        ),
    ]
