# Generated by Django 5.1.4 on 2025-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoldingMainMenu', '0006_alter_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
