# Generated by Django 5.1.4 on 2025-02-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HoldingMainMenu', '0003_emploees_holding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('account_type', models.IntegerField()),
                ('auntificatiuon', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserMainMenu.users')),
            ],
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HoldingMainMenu.venues')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserMainMenu.wishlist')),
            ],
        ),
    ]
