# Generated by Django 5.1.4 on 2025-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_user_two_factor_auth_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_veryfy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
